webserver:
  host: 127.0.0.1
  port: 5432

dicomserver:
  host: 127.0.0.1
  port: 5432
  aetitle: aetele
  aeremote: aeremote-tele
  filepath: ./storage/dicom/
 
database:
 name: grm
 user: postgres
 password: emao

secret: 
  secret : 0ifp5bw(!1j8bq#2bwd24)bn!0$gco6hhoce^!7tmprdaf$1z7
